# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='fromp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromFriendSet', to='org.Profile', verbose_name='发起者'),
        ),
    ]
