# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20170125_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAccessed', models.BooleanField(default=True, verbose_name='是否通过好友请求')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isHost',
        ),
        migrations.AddField(
            model_name='profile',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='是否禁用'),
        ),
    ]
