# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_remove_profile_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
