# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170123_0237'),
        ('org', '0007_profile_childpwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classGroup',
        ),
        migrations.AddField(
            model_name='profile',
            name='classGroups',
            field=models.ManyToManyField(null=True, to='school.ClassGroup'),
        ),
    ]
