# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'verbose_name': 'B.班级', 'verbose_name_plural': 'B.班级'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'A.学校', 'verbose_name_plural': 'A.学校'},
        ),
    ]
