# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaresource',
            options={'verbose_name': '媒体文件', 'verbose_name_plural': '媒体文件'},
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='mediaType',
            field=models.CharField(choices=[('img', '图像'), ('audio', '声音'), ('video', '视频')], max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名称'),
        ),
    ]
