# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('org', '0001_initial'),
        ('habitinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentDate', models.DateTimeField(auto_now_add=True, verbose_name='点评日期')),
                ('commentType', models.CharField(choices=[('prase', '赞扬'), ('txt', '留言'), ('sound', '语音'), ('money', '打赏')], max_length=10)),
                ('audioUrls', models.CharField(default='', max_length=1024, verbose_name='音频')),
                ('content', models.CharField(blank=True, max_length=150, null=True)),
                ('moneyPraseAmount', models.IntegerField(default=0, verbose_name='打赏金额')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fromProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Profile', verbose_name='点评者')),
            ],
            options={
                'verbose_name_plural': 'C.点评',
                'verbose_name': 'C.点评',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedDate', models.DateField(auto_now_add=True, verbose_name='打卡日期')),
                ('freeMily', models.IntegerField(default=0, verbose_name='打卡得米')),
                ('accumDays', models.IntegerField(default=0, verbose_name='累积天数')),
                ('accumMily', models.IntegerField(default=0, verbose_name='累积得米')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitinfo.Habit', verbose_name='习惯')),
            ],
            options={
                'verbose_name_plural': 'A.打卡',
                'verbose_name': 'A.打卡',
            },
        ),
        migrations.CreateModel(
            name='OrgActivityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('habits', models.CharField(blank=True, max_length=150, null=True, verbose_name='习惯')),
                ('isFree', models.BooleanField(default=True, verbose_name='是否免费')),
                ('fee', models.IntegerField(default=0, verbose_name='收费金额')),
                ('lazyFund', models.IntegerField(default=0, verbose_name='懒人基金')),
                ('enableLazyFund', models.BooleanField(default=False, verbose_name='是否参与懒人基金')),
                ('activityDays', models.IntegerField(default=0, verbose_name='持续天数')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org', verbose_name='家庭')),
            ],
            options={
                'verbose_name_plural': 'C.家庭活动历史',
                'verbose_name': 'C.家庭活动历史',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateField(auto_now_add=True, verbose_name='发帖日期')),
                ('content', models.CharField(blank=True, max_length=150, null=True)),
                ('feel', models.CharField(default='PJ', max_length=4, verbose_name='心情')),
                ('imgUrl', models.CharField(default='http://mily365.com/media/upload/mily.png', max_length=256, verbose_name='反馈图片')),
                ('audioUrls', models.CharField(default='', max_length=1024, verbose_name='音频')),
                ('accumPrases', models.IntegerField(default=0, verbose_name='累积赞')),
                ('accumAudios', models.IntegerField(default=0, verbose_name='累积语音')),
                ('accumMonkeys', models.IntegerField(default=0, verbose_name='累积打赏')),
                ('accumContents', models.IntegerField(default=0, verbose_name='累积内容')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('feedBack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedBack', verbose_name='时光记录')),
            ],
            options={
                'verbose_name_plural': 'B.发帖',
                'verbose_name': 'B.发帖',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='orgActivityHistory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.OrgActivityHistory', verbose_name='家庭个人历史习惯'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Profile', verbose_name='打卡者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Post', verbose_name='点评'),
        ),
    ]
