# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0013_auto_20170125_1649'),
        ('media', '0001_initial'),
        ('habitinfo', '0004_remove_habitcatalog_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentDate', models.DateTimeField(auto_now_add=True, verbose_name='点评日期')),
                ('commentType', models.CharField(choices=[('prase', '赞扬'), ('sound', '语音'), ('money', '打赏')], max_length=10)),
                ('content', models.CharField(blank=True, max_length=150, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedDate', models.DateField(auto_now_add=True, verbose_name='打卡日期')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='OrgHabitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitinfo.Habit', verbose_name='习惯')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': 'C.家庭习惯历史',
                'verbose_name_plural': 'C.家庭习惯历史',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateField(auto_now_add=True, verbose_name='发帖日期')),
                ('content', models.CharField(blank=True, max_length=150, null=True)),
                ('accumPrases', models.IntegerField(default=0, verbose_name='累积赞')),
                ('accumAudios', models.IntegerField(default=0, verbose_name='累积打赏')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('feedBack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedBack', verbose_name='时光记录')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='活动')),
            ],
        ),
    ]
