# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('feedback', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orghabithistory',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org', verbose_name='家庭'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='orgHabitHistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.OrgHabitHistory', verbose_name='家庭个人历史习惯'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Profile', verbose_name='打卡者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fromProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Profile', verbose_name='点评者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Post', verbose_name='点评'),
        ),
    ]
