# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20170125_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'C.点评', 'verbose_name_plural': 'C.点评'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'A.打卡', 'verbose_name_plural': 'A.打卡'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'B.发帖', 'verbose_name_plural': 'B.发帖'},
        ),
    ]
