# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20170125_2204'),
        ('org', '0003_auto_20170125_2204'),
        ('feedback', '0003_auto_20170125_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgActivityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('habits', models.CharField(blank=True, max_length=150, null=True, verbose_name='习惯')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org', verbose_name='家庭')),
            ],
            options={
                'verbose_name_plural': 'C.家庭活动历史',
                'verbose_name': 'C.家庭活动历史',
            },
        ),
        migrations.RemoveField(
            model_name='orghabithistory',
            name='Habit',
        ),
        migrations.RemoveField(
            model_name='orghabithistory',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='orghabithistory',
            name='org',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='orgHabitHistory',
        ),
        migrations.DeleteModel(
            name='OrgHabitHistory',
        ),
        migrations.AddField(
            model_name='feedback',
            name='orgActivityHistory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.OrgActivityHistory', verbose_name='家庭个人历史习惯'),
        ),
    ]
