# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20170215_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgactivityhistory',
            name='enableLazyFund',
            field=models.BooleanField(default=False, verbose_name='是否参与懒人基金'),
        ),
        migrations.AddField(
            model_name='orgactivityhistory',
            name='lazyFund',
            field=models.IntegerField(default=0, verbose_name='懒人基金'),
        ),
    ]
