# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20170311_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgactivityhistory',
            name='getMily',
            field=models.IntegerField(default=0, verbose_name='活动赠米'),
        ),
        migrations.AddField(
            model_name='orgactivityhistory',
            name='isFree',
            field=models.BooleanField(default=True, verbose_name='是否免费'),
        ),
    ]
