# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_orgactivityhistory_activitydays'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgactivityhistory',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='收费金额'),
        ),
    ]
