# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_orgactivityhistory_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='accumMonkeys',
            field=models.IntegerField(default=0, verbose_name='累积打赏'),
        ),
        migrations.AddField(
            model_name='post',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='反馈图片'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='音频'),
        ),
        migrations.AlterField(
            model_name='post',
            name='accumAudios',
            field=models.IntegerField(default=0, verbose_name='累积语音'),
        ),
    ]
