# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20170408_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgUrl',
            field=models.CharField(default='http://mily365.com/media/upload/mily.png', max_length=256, verbose_name='反馈图片'),
        ),
    ]
