# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_auto_20170408_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feedBack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedBack', verbose_name='时光记录'),
        ),
    ]
