# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0012_auto_20170408_2052'),
        ('feedback', '0012_auto_20170408_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitinfo.Habit', verbose_name='习惯'),
        ),
    ]
