# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_feedback_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='accumDays',
            field=models.IntegerField(default=0, verbose_name='累积天数'),
        ),
    ]
