# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_feedback_accumdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='accumMily',
            field=models.IntegerField(default=0, verbose_name='累积得米'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='freeMily',
            field=models.IntegerField(default=0, verbose_name='打卡得米'),
        ),
    ]
