# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_auto_20170409_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audioUrls',
            field=models.CharField(default='', max_length=1024, verbose_name='反馈图片'),
        ),
    ]
