# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_post_audiourls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audioUrls',
            field=models.CharField(default='', max_length=1024, verbose_name='音频'),
        ),
    ]
