# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_post_feel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='audio',
        ),
        migrations.AddField(
            model_name='comment',
            name='audioUrls',
            field=models.CharField(default='', max_length=1024, verbose_name='音频'),
        ),
    ]
