# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_auto_20170416_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moneyPraseAmount',
            field=models.IntegerField(default=0, verbose_name='打赏金额'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentType',
            field=models.CharField(choices=[('prase', '赞扬'), ('txt', '留言'), ('sound', '语音'), ('money', '打赏')], max_length=10),
        ),
    ]
