# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('feedback', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(choices=[('cash', '现金'), ('rice', '米粒'), ('deposit', '押金')], max_length=50, verbose_name='账户类型')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='余额')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人钱包',
                'verbose_name_plural': '个人钱包',
            },
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeDate', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('tradeType', models.CharField(choices=[('fee', '套餐服务费'), ('deposit', '押金'), ('milyOutput', '米粒打赏'), ('milyOutputByDonate', '米粒捐赠'), ('feedBackMilyInput', '打卡奖励米粒'), ('feedBackReturnDeposit', '打卡返还押金'), ('aveDeposit', '平均分配懒人押金'), ('takeCash', '用户提现')], max_length=50, verbose_name='类型')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='套餐服务费')),
                ('tradeAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='交易额')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='个人钱包')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedBack', verbose_name='打卡信息')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Profile', verbose_name='责任人')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org', verbose_name='家庭')),
            ],
            options={
                'verbose_name': '个人账务',
                'verbose_name_plural': '个人账务',
            },
        ),
        migrations.CreateModel(
            name='SysAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='账户名称')),
                ('accountType', models.CharField(choices=[('cash', '现金'), ('rice', '米粒'), ('deposit', '押金')], max_length=50, verbose_name='账户类型')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='余额')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统账户',
                'verbose_name_plural': '系统账户',
            },
        ),
        migrations.CreateModel(
            name='SysAccountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeDate', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('tradeType', models.CharField(choices=[('sysFillMily', '平台生产米粒'), ('sysFreeOutMily', '平台免费赠送米粒'), ('sysFreeInputMily', '平台免费赠送退回米粒'), ('sysTakeCash', '平台提现'), ('sysInitCash', '平台预存')], max_length=50, verbose_name='类型')),
                ('tradeAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='交易额')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sysAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SysAccount', verbose_name='系统账户')),
            ],
            options={
                'verbose_name': '系统账务',
                'verbose_name_plural': '系统账务',
            },
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='sysAccountHistory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SysAccountHistory', verbose_name='平台账务'),
        ),
    ]
