# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='tradeType',
            field=models.CharField(choices=[('fee', '套餐服务费'), ('deposit', '押金'), ('milyOutput', '米粒打赏'), ('milyOutputByDonate', '米粒捐赠'), ('feedBackMilyInput', '打卡奖励米粒'), ('feedBackMilyInputCancel', '打卡奖励米粒取消'), ('feedBackReturnDeposit', '打卡返还押金'), ('aveDeposit', '平均分配懒人押金'), ('takeCash', '用户提现')], max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='sysaccounthistory',
            name='tradeType',
            field=models.CharField(choices=[('sysFillMily', '平台生产米粒'), ('sysFreeOutMily', '平台免费赠送米粒'), ('sysFreeOutMilyCancel', '平台免费赠送米粒取消'), ('sysFreeInputMily', '平台免费赠送退回米粒'), ('sysTakeCash', '平台提现'), ('sysInitCash', '平台预存')], max_length=50, verbose_name='类型'),
        ),
    ]
