# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('account', '0002_account_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Profile', verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='account',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org', verbose_name='家庭'),
        ),
    ]
