# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170125_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '账务', 'verbose_name_plural': '账务'},
        ),
    ]
