# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_remove_profile_disabled'),
        ('account', '0006_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cash', '现金'), ('rice', '米粒')], max_length=50, verbose_name='账户名称')),
                ('accountType', models.CharField(choices=[('cash', '现金'), ('rice', '米粒')], max_length=50, verbose_name='账户类型')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='余额')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '系统账户',
                'verbose_name': '系统账户',
            },
        ),
        migrations.CreateModel(
            name='SysAccountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeDate', models.DateField(auto_now=True, verbose_name='时间')),
                ('tradeType', models.CharField(choices=[('fee', '套餐服务费'), ('deposit', '押金'), ('milyInput', '套餐囤米'), ('milyInputByDeposit', '押金囤米'), ('milyOutput', '米粒打赏'), ('milyOutputByDonate', '米粒捐赠'), ('feedBack', '打卡奖励米粒'), ('feedBackReturnDeposit', '打卡返还押金'), ('aveDeposit', '平均分配懒人押金'), ('takeCash', '用户提现'), ('sysFillMily', '系统生产米粒'), ('sysTakeCash', '系统提现')], max_length=50, verbose_name='类型')),
                ('tradeAmount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='交易额')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sysAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SysAccount', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '系统账务',
                'verbose_name': '系统账务',
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '个人钱包', 'verbose_name_plural': '个人钱包'},
        ),
        migrations.AlterModelOptions(
            name='accounthistory',
            options={'verbose_name': '个人账务', 'verbose_name_plural': '个人账务'},
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='aveDeposit',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='feedBack',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='feedBackReturnDeposit',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='milyInput',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='milyInputByDeposit',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='milyOutput',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='milyOutputByDonate',
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Profile', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='tradeAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='交易额'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='套餐服务费'),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='tradeType',
            field=models.CharField(choices=[('fee', '套餐服务费'), ('deposit', '押金'), ('milyInput', '套餐囤米'), ('milyInputByDeposit', '押金囤米'), ('milyOutput', '米粒打赏'), ('milyOutputByDonate', '米粒捐赠'), ('feedBack', '打卡奖励米粒'), ('feedBackReturnDeposit', '打卡返还押金'), ('aveDeposit', '平均分配懒人押金'), ('takeCash', '用户提现'), ('sysFillMily', '系统生产米粒'), ('sysTakeCash', '系统提现')], max_length=50, verbose_name='类型'),
        ),
    ]
