# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170312_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='sysaccounthistory',
            name='sysAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SysAccount', verbose_name='系统账户'),
        ),
        migrations.AlterField(
            model_name='sysaccounthistory',
            name='tradeAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='交易额'),
        ),
    ]
