# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170312_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysaccount',
            name='name',
            field=models.CharField(max_length=50, verbose_name='账户名称'),
        ),
    ]
