# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170312_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysaccounthistory',
            name='tradeDate',
            field=models.DateField(verbose_name='时间'),
        ),
    ]
