# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170312_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='个人钱包'),
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='sysAccountHistory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SysAccountHistory', verbose_name='平台账务'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.CharField(choices=[('cash', '现金'), ('rice', '米粒'), ('rice', '押金')], max_length=50, verbose_name='账户类型'),
        ),
        migrations.AlterField(
            model_name='sysaccount',
            name='accountType',
            field=models.CharField(choices=[('cash', '现金'), ('rice', '米粒'), ('rice', '押金')], max_length=50, verbose_name='账户类型'),
        ),
    ]
