# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170312_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.CharField(choices=[('cash', '现金'), ('rice', '米粒'), ('deposit', '押金')], max_length=50, verbose_name='账户类型'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='sysaccount',
            name='accountType',
            field=models.CharField(choices=[('cash', '现金'), ('rice', '米粒'), ('deposit', '押金')], max_length=50, verbose_name='账户类型'),
        ),
    ]
