# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('score', models.IntegerField(verbose_name='分值临界点')),
                ('cat', models.CharField(choices=[('B', '体力'), ('L', '爱心')], max_length=4, verbose_name='称号分类')),
            ],
            options={
                'verbose_name_plural': 'A.称号',
                'verbose_name': 'A.称号',
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount_feeratio', models.IntegerField(default=7, verbose_name='费率(千分之几)')),
            ],
            options={
                'verbose_name_plural': 'B.系统计算参数',
                'verbose_name': 'B.系统计算参数',
            },
        ),
    ]
