# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honor',
            options={'verbose_name': 'A.称号', 'verbose_name_plural': 'A.称号'},
        ),
        migrations.AlterModelOptions(
            name='params',
            options={'verbose_name': 'B.系统计算参数', 'verbose_name_plural': 'B.系统计算参数'},
        ),
    ]
