# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0002_auto_20170123_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='params',
            old_name='amount_MoneyUnit',
            new_name='amount_moneyUnit',
        ),
        migrations.AddField(
            model_name='params',
            name='amount_feeratio',
            field=models.IntegerField(default=0, verbose_name='费率(千分之几)'),
        ),
    ]
