# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0003_auto_20170125_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='amount_feedUnit',
        ),
        migrations.RemoveField(
            model_name='params',
            name='amount_moneyUnit',
        ),
        migrations.AlterField(
            model_name='params',
            name='amount_feeratio',
            field=models.IntegerField(default=7, verbose_name='费率(千分之几)'),
        ),
    ]
