# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitcatalog',
            name='question',
            field=models.CharField(default='f', max_length=256, verbose_name='了解问题'),
        ),
    ]
