# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('code',), 'verbose_name': 'B.习惯', 'verbose_name_plural': 'B.习惯'},
        ),
        migrations.AlterModelOptions(
            name='habitcatalog',
            options={'verbose_name': 'A.分类', 'verbose_name_plural': 'A.分类'},
        ),
    ]
