# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20170123_1130'),
        ('habitinfo', '0002_auto_20170123_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitcatalog',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity', verbose_name='所属活动'),
        ),
    ]
