# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0003_habitcatalog_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitcatalog',
            name='activity',
        ),
    ]
