# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0004_remove_habitcatalog_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='freePraiseMilyStep',
            field=models.IntegerField(default=0, verbose_name='打卡奖励步进数'),
        ),
        migrations.AddField(
            model_name='habit',
            name='freePraiseMilyUnit',
            field=models.IntegerField(default=0, verbose_name='打卡奖励基数'),
        ),
    ]
