# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0005_auto_20170325_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='freePraiseMilyUnit',
            field=models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500'), (600, '600')], default=0, verbose_name='打卡奖励基数'),
        ),
    ]
