# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0006_auto_20170325_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitcatalog',
            name='forParent',
            field=models.BooleanField(default=False, verbose_name='是否父母专用'),
        ),
    ]
