# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0007_habitcatalog_forparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='level',
            field=models.CharField(choices=[('sun', '生活'), ('honest', '诚实'), ('share', '分享'), ('thank', '感恩'), ('read', '阅读'), ('sport', '运动')], default='sun', max_length=64, verbose_name='难度'),
        ),
    ]
