# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0008_auto_20170329_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='level',
            field=models.CharField(choices=[('fa fa-sun-o sun', '生活'), ('fa fa-diamond diamond', '诚实'), ('fa fa-share-alt', '分享'), ('fa fa-birthday-cake thank', '感恩'), ('fa fa-book read', '阅读'), ('fa fa-bicycle', '运动')], default='fa fa-sun-o sun', max_length=64, verbose_name='难度'),
        ),
    ]
