# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0011_auto_20170404_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.CharField(choices=[('fa fa-sun-o fa-lg sun', '生活'), ('fa fa-diamond fa-lg diamond', '诚实'), ('fa fa-share-alt fa-lg', '分享'), ('fa fa-birthday-cake fa-lg thank', '感恩'), ('fa fa-book fa-lg read', '阅读'), ('fa fa-bicycle fa-lg', '运动')], default='fa fa-sun-o sun', max_length=64, verbose_name='图标'),
        ),
    ]
