# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='编码')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('0', '停用'), ('1', '启用')], default='1', max_length=2, verbose_name='状态')),
                ('usage', models.CharField(choices=[('0', '移动'), ('1', 'ＰＣ')], default='0', max_length=2, verbose_name='用途')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='主题')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='概述')),
                ('imgResource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '首页轮换图',
                'verbose_name': '首页轮换图',
            },
        ),
        migrations.CreateModel(
            name='WxWelcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('desc', models.CharField(max_length=100, verbose_name='概述')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '微信欢迎',
                'verbose_name': '微信欢迎',
            },
        ),
    ]
