# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_auto_20170125_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxWelcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('desc', models.CharField(max_length=100, verbose_name='概述')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='图片')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
