# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_wxwelcome_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxwelcome',
            options={'verbose_name': '微信欢迎', 'verbose_name_plural': '微信欢迎'},
        ),
    ]
