# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20170125_2204'),
        ('cms', '0004_auto_20170404_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('0', '停用'), ('1', '启用')], default='1', max_length=2, verbose_name='状态')),
                ('usage', models.CharField(choices=[('0', '停用'), ('1', '启用')], default='0', max_length=2, verbose_name='用途')),
                ('desc', models.CharField(max_length=100, verbose_name='概述')),
                ('imgResource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='图片')),
            ],
            options={
                'verbose_name': '首页轮换图',
                'verbose_name_plural': '首页轮换图',
            },
        ),
    ]
