# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_loophead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loophead',
            name='usage',
            field=models.CharField(choices=[('0', '移动'), ('1', 'ＰＣ')], default='0', max_length=2, verbose_name='用途'),
        ),
    ]
