# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170416_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loophead',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='概述'),
        ),
        migrations.AlterField(
            model_name='loophead',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主题'),
        ),
    ]
