# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitinfo', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('startTime', models.DateTimeField(verbose_name='开始日期')),
                ('endTime', models.DateTimeField(verbose_name='结束日期')),
                ('cat', models.CharField(choices=[('FEE', '收费'), ('FREE', '免费'), ('DONATE', '捐赠'), ('Market', '市场')], max_length=20, verbose_name='类别')),
                ('desc', models.CharField(max_length=20, null=True, verbose_name='关键词')),
                ('applyNumber', models.IntegerField(default=0, editable=False, verbose_name='已报名人数')),
                ('uplimit', models.IntegerField(default=0, verbose_name='人数上限')),
                ('amount', models.IntegerField(default=0, verbose_name='报名费')),
                ('rtnLazyUnit', models.IntegerField(choices=[(1, '1元'), (2, '２元'), (3, '３元'), (5, '５元'), (8, '８元'), (10, '10元')], default=1, verbose_name='每日打卡返回押金')),
                ('lazyFund', models.IntegerField(default=0, verbose_name='懒人基金')),
                ('lazyJoinNumber', models.IntegerField(default=0, verbose_name='已经参与懒人计划人数')),
                ('days', models.IntegerField(default=0, verbose_name='活动天数')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (-1, '已结束')], default=0, verbose_name='活动状态')),
                ('isTop', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('memo', models.TextField(max_length=2048, verbose_name='注意事项')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '活动',
                'verbose_name': '活动',
            },
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exceptionCount', models.IntegerField(default=0, verbose_name='允许请假天数')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitinfo.HabitCatalog', verbose_name='习惯类别')),
            ],
            options={
                'verbose_name_plural': '活动项目',
                'verbose_name': '活动项目',
            },
        ),
    ]
