# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img',
            field=models.ImageField(upload_to='/media', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='memo',
            field=models.TextField(max_length=500, verbose_name='备注'),
        ),
    ]
