# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20170123_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
