# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20170123_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityitem',
            name='habitCatalog',
        ),
        migrations.DeleteModel(
            name='ActivityItem',
        ),
    ]
