# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitinfo', '0004_remove_habitcatalog_activity'),
        ('activity', '0006_activityitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityitem',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitinfo.HabitCatalog', verbose_name='习惯类别'),
        ),
    ]
