# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20170123_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityitem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='activityitem',
            name='name',
        ),
    ]
