# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20170123_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='img',
            field=models.ImageField(upload_to='upload/', verbose_name='活动图片'),
        ),
    ]
