# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20170123_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityitem',
            name='exceptionCount',
            field=models.IntegerField(default=0, verbose_name='允许请假天数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaResource', verbose_name='活动'),
        ),
    ]
