# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20170125_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cat',
            field=models.CharField(choices=[('FEE', '收费'), ('FREE', '免费'), ('DONATE', '捐赠'), ('Market', '市场')], max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.DateTimeField(verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.DateTimeField(verbose_name='开始日期'),
        ),
    ]
