# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_auto_20170227_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='applyNumber',
            field=models.IntegerField(default=0, editable=False, verbose_name='已报名人数'),
        ),
        migrations.AddField(
            model_name='activity',
            name='uplimit',
            field=models.IntegerField(default=0, verbose_name='人数上限'),
        ),
    ]
