# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_activity_zeroablemily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (-1, '已结束')], default=0, verbose_name='活动状态'),
        ),
    ]
