# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_remove_activity_zeroablemily'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rtnLazyUnit',
            field=models.IntegerField(default=1, verbose_name='每日打卡返回押金'),
        ),
    ]
