# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_activity_rtnlazyunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='days',
            field=models.IntegerField(default=0, verbose_name='活动天数'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lazyFund',
            field=models.IntegerField(default=0, verbose_name='懒人基金'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lazyJoinNumber',
            field=models.IntegerField(default=0, verbose_name='已经参与懒人计划人数'),
        ),
    ]
