# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_auto_20170330_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rtnLazyUnit',
            field=models.IntegerField(choices=[(1, '1元'), (2, '２元'), (3, '３元'), (5, '５元'), (8, '８元'), (10, '10元')], default=1, verbose_name='每日打卡返回押金'),
        ),
    ]
